name: CI/CD actions
on: [push]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      -
        name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Push to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: ENV=production
          tags: ${{ secrets.DOCKER_USERNAME }}/althingi-source-db:${{ github.sha }}, ${{ secrets.DOCKER_USERNAME }}/althingi-source-db:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      # -
      #   name: Deploy container to server
      #   uses: appleboy/ssh-action@master
      #   with:
      #     script: /var/app/bin/aggregator
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USER }}
      #     passphrase: ${{ secrets.SSH_PASSPHRASE }}
      #     key: ${{ secrets.SSH_KEY }}


